# Generated by Django 5.2.4 on 2025-07-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
