# Generated by Django 5.2.4 on 2025-08-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="actual_delivery",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="review_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="review_reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
