# Generated by Django 4.2.7 on 2025-07-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
