# Generated by Django 4.2.7 on 2025-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_review_is_verified_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_submitted",
            field=models.BooleanField(default=True),
        ),
    ]
