# Generated by Django 5.2.4 on 2025-08-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_actual_delivery_order_carrier_and_more"),
        ("products", "0004_review_is_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="orders.order",
            ),
        ),
    ]
