# Generated by Django 5.2.4 on 2025-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_stock_quantity_productvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
