# Generated by Django 5.2.4 on 2025-08-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productvariant_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
