# Generated by Django 5.2.4 on 2025-08-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                ],
                max_length=20,
            ),
        ),
    ]
